version: '3.1'

services:

  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dev
      - APP_DB_USER=springbootapp
      - APP_DB_PASS=password
      - APP_DB_NAME=springbootapp
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

networks:
  boot-app:
