info:
  app:
    name: Sample Spring Boot App
    version: 1.0

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /
  endpoint:
    beans:
      cache:
        time-to-live: 10s
    health:
      show-details: always

spring:
  application:
    name: spring-boot-app
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootapp
    username: springbootapp
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # Tables creation from JPA definitions. Would want flyway / liquibase to manage for a serious application.
    open-in-view: false

health:
  default-ping-path: /ping

web:
  client:
    connect-timeout-ms: 20000
    read-timeout-ms: 5000
    write-timeout-ms: 5000
    document-byte-buffer-size: 20971520

base:
  url: "https://jsonplaceholder.typicode.com"
