info:
  app:
    name: Sample Spring Boot App
    version: 1.0

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /
  endpoint:
    beans:
      cache:
        time-to-live: 10s
    health:
      show-details: always

spring:
  application:
    name: spring-boot-app
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        ddl-auto: create
  sql:
    init:
      platform: h2
      mode: always

health:
  default-ping-path: /ping

web:
  client:
    connect-timeout-ms: 20000
    read-timeout-ms: 5000
    write-timeout-ms: 5000
    document-byte-buffer-size: 20971520
