info:
  app:
    name: Sample Spring Boot App
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /
  endpoint:
    beans:
      cache:
        time-to-live: 10s
    health:
      show-details: always

spring:
  application:
    name: spring-boot-app

health:
  default-ping-path: /ping

web:
  client:
    connect-timeout-ms: 20000
    read-timeout-ms: 5000
    write-timeout-ms: 5000
    document-byte-buffer-size: 20971520
